INSERT INTO exercises (name, target, category, kanji, description, difficulty) VALUES
('Shadow Push', 'Chest', 'push', '押', 'Explosive push-up variation that builds chest and tricep power', 'beginner'),
('Samurai Row', 'Back', 'pull', '引', 'Bent-over row with controlled tempo, building back thickness', 'intermediate'),
('Iron Squat', 'Quads', 'legs', '屈', 'Deep bodyweight squat for leg strength and mobility', 'beginner'),
('Crimson Press', 'Shoulders', 'push', '肩', 'Overhead press for deltoid strength and stability', 'intermediate'),
('Steel Deadlift', 'Hamstrings', 'pull', '腰', 'Hip hinge movement for posterior chain development', 'warrior'),
('Core Strike', 'Abs', 'core', '腹', 'High-rep core exercise targeting the entire midsection', 'beginner'),
('Blade Curl', 'Biceps', 'pull', '腕', 'Isolated bicep curl with strict form', 'intermediate'),
('Dojo Dip', 'Triceps', 'push', '伸', 'Tricep dip on parallel bars or bench', 'intermediate'),
('Ronin Lunge', 'Glutes', 'legs', '突', 'Walking lunge for glutes and quad development', 'beginner'),
('Warrior Pull-up', 'Lats', 'pull', '上', 'Pull-up or assisted pull-up for lat width', 'warrior'),
('Dragon Fly', 'Lower Back', 'core', '龍', 'Superman hold for spinal erectors and glutes', 'intermediate'),
('Temple Plank', 'Core', 'core', '寺', 'Extended plank hold for core endurance', 'beginner'),
('Silent Stretch', 'Hamstrings', 'core', '静', 'Forward fold with controlled breathing and hamstring stretch', 'beginner'),
('Storm Burpee', 'Full Body', 'full', '嵐', 'Full burpee with push-up and explosive jump', 'warrior'),
('Rising Sun', 'Calves', 'legs', '昇', 'Calf raise on elevated surface for lower leg power', 'beginner'),
('Ichiban Closer', 'Chest', 'push', '一', 'Chest fly movement for inner chest definition', 'intermediate'),
('Hollow Hold', 'Abs', 'core', '空', 'Isometric hollow body hold for core strength', 'intermediate'),
('Windmill', 'Obliques', 'core', '風', 'Standing oblique reach for waist mobility and strength', 'intermediate'),
('Fudo Stance', 'Glutes', 'legs', '不', 'Wall sit hold for isometric leg endurance', 'beginner'),
('Kensei Press', 'Shoulders', 'push', '剣', 'Lateral raise for shoulder width and definition', 'intermediate'),
('Water Flow', 'Back', 'pull', '水', 'Lat pulldown or pull-up variation for back width', 'intermediate'),
('Mountain Hold', 'Core', 'core', '山', 'Static mountain climber hold position', 'intermediate'),
('Thunder Clap', 'Chest', 'push', '雷', 'Explosive clap push-up for power', 'warrior'),
('Bamboo Reach', 'Lats', 'pull', '竹', 'Straight-arm pulldown for lat isolation', 'intermediate'),
('Crane Balance', 'Core', 'core', '鶴', 'Single-leg balance hold with core engagement', 'beginner'),
('Fire Breath', 'Conditioning', 'cardio', '火', 'High-knee sprint for cardiovascular conditioning', 'intermediate'),
('Iron Fist', 'Forearms', 'pull', '拳', 'Wrist curl or farmers carry for grip strength', 'beginner'),
('Shadow Spar', 'Full Body', 'full', '影', 'Shadow boxing circuit combining punches and footwork', 'warrior'),
('Stone Wall', 'Chest', 'push', '石', 'Isometric chest press hold against resistance', 'beginner'),
('Zen Reach', 'Shoulders', 'pull', '禅', 'Deep shoulder stretch with controlled movement', 'beginner'),
('Oni Slam', 'Full Body', 'full', '鬼', 'Slam a medicine ball or imaginary object for explosive power', 'warrior'),
('Serpent Twist', 'Obliques', 'core', '蛇', 'Russian twist for oblique carving and rotational power', 'intermediate'),
('Phoenix Rise', 'Glutes', 'legs', '鳳', 'Glute bridge raise for hip extension and glute activation', 'beginner'),
('Tiger Stance', 'Quads', 'legs', '虎', 'Wide stance squat holding at parallel for isometric burn', 'intermediate'),
('Dragon Punch', 'Shoulders', 'push', '拳', 'Alternating shoulder punch-outs for speed and endurance', 'intermediate'),
('Lotus Hold', 'Hips', 'core', '蓮', 'Deep hip flexor stretch hold in lotus position', 'beginner'),
('Wave Crash', 'Core', 'core', '波', 'Rolling crunch like ocean waves for spinal articulation', 'intermediate'),
('Moon Crescent', 'Obliques', 'core', '月', 'Side bend reaching like a crescent moon', 'beginner'),
('Star Burst', 'Full Body', 'full', '星', 'Star jump from squat for explosive full body power', 'warrior'),
('Void Pull', 'Back', 'pull', '虚', 'Face pull for rear delts and posture improvement', 'intermediate'),
('Earth Push', 'Chest', 'push', '地', 'Incline push-up variation targeting upper chest', 'beginner'),
('Heaven Press', 'Shoulders', 'push', '天', 'Arnold press for full deltoid engagement', 'intermediate'),
('Spirit Bridge', 'Glutes', 'legs', '霊', 'Single-leg glute bridge for unilateral strength', 'intermediate'),
('Demon Grip', 'Forearms', 'pull', '魔', 'Dead hang for grip endurance and decompression', 'beginner'),
('Blade Runner', 'Quads', 'legs', '刃', 'High knee running in place for leg power and cardio', 'intermediate'),
('Night Stalker', 'Hamstrings', 'legs', '夜', 'Reverse lunge with hamstring focus', 'intermediate'),
('Dawn Breaker', 'Full Body', 'full', '暁', 'Burpee with tuck jump for morning explosive activation', 'warrior'),
('Storm Caller', 'Back', 'pull', '嵐', 'Renegade row combining plank with alternating rows', 'warrior'),
('Wind Cutter', 'Core', 'core', '風', 'Bicycle crunch for oblique and rectus abdominis', 'intermediate'),
('Shadow Step', 'Glutes', 'legs', '歩', 'Lateral lunge step for hip mobility and outer glutes', 'beginner'),
('Fist of Steel', 'Biceps', 'pull', '鋼', 'Hammer curl for brachialis and forearm integration', 'intermediate'),
('Rising Dragon', 'Full Body', 'full', '昇', 'Standing to sprawl to explosive jump sequence', 'warrior'),
('Silent Night', 'Core', 'core', '静', 'Deep breathing plank hold with meditation focus', 'beginner');
